// Complete Product Catalog with all products from Conquerr Healthcare
const productCategories = {
    syringes: {
        name: "Syringes & Needles",
        description: "High-quality disposable syringes and needles for medical professionals",
        image: "syringes.png",
        icon: "fa-syringe",
        products: [
            { id: 1, name: "Disposable Needles 18G x 1.5\"", sku: "NEE-18G-1.5", unit: "100s", price: 180.00 },
            { id: 2, name: "Disposable Needles 21G x 1.5\"", sku: "NEE-21G-1.5", unit: "100s", price: 140.00 },
            { id: 3, name: "Disposable Needles 23G x 1\"", sku: "NEE-23G-1", unit: "100s", price: 140.00 },
            { id: 4, name: "Microfine Syringes 1ml Unibody with 29G/30G Needle", sku: "MIC-1ML-UNI", unit: "100s", price: 2600.00 },
            { id: 5, name: "Microfine Syringes 0.5ml Unibody with 29G/30G Needle", sku: "MIC-0.5ML-UNI", unit: "100s", price: 2600.00 },
            { id: 6, name: "Plastipak Syringe 1 ML", sku: "PLA-1ML", unit: "100s", price: 2670.00 },
            { id: 7, name: "Spinal Needle Quinckle 90mm 22G", sku: "SPI-22G-90", unit: "50s", price: 3340.00 },
            { id: 8, name: "Spinal Needle Quinckle 90mm 25G", sku: "SPI-25G-90", unit: "50s", price: 3340.00 },
            { id: 9, name: "Soloshot 0.05ml Syringes", sku: "SOL-0.05ML", unit: "100s", price: 3340.00 },
            { id: 10, name: "Soloshot 0.5ml Syringes", sku: "SOL-0.5ML", unit: "100s", price: 2940.00 },
            { id: 11, name: "Syringe 10ml With 21G x1.5\" Needle", sku: "SYR-10ML-21G", unit: "100s", price: 670.00 },
            { id: 12, name: "Syringe 10ml Without Needle", sku: "SYR-10ML-NO", unit: "100s", price: 560.00 },
            { id: 13, name: "Syringe 20ml Without Needle", sku: "SYR-20ML-NO", unit: "50s", price: 460.00 },
            { id: 14, name: "Syringe 2ml With 23G x 1'' Needle", sku: "SYR-2ML-23G", unit: "100s", price: 400.00 },
            { id: 15, name: "Syringe 2ml Without Needle", sku: "SYR-2ML-NO", unit: "100s", price: 320.00 },
            { id: 16, name: "Syringe 5ml With 21G x1.5\" Needle", sku: "SYR-5ML-21G", unit: "100s", price: 410.00 },
            { id: 17, name: "Syringe 5ml Without Needle", sku: "SYR-5ML-NO", unit: "100s", price: 340.00 },
            { id: 18, name: "Syringes 20ml with 21G x 1.5\" Needle", sku: "SYR-20ML-21G", unit: "50s", price: 580.00 },
            { id: 19, name: "Syringes 60ml with Catheter Tip", sku: "SYR-60ML-CAT", unit: "25s", price: 1200.00 }
        ]
    },
    bandages: {
        name: "Bandages, Tapes & Dressings",
        description: "Comprehensive range of medical dressings and wound care supplies",
        image: "bandages.png",
        icon: "fa-bandage",
        products: [
            { id: 1, name: "Adhesive Elastic Fabric Bandage Waterproof (76x19mm)", sku: "AEF-76X19", unit: "100s", price: 110.00 },
            { id: 2, name: "Adhesive Non-Woven Wound Dressing 25x10cm", sku: "ANW-25X10", unit: "40s", price: 420.00 },
            { id: 3, name: "Adhesive PU Wound Dressing 25x10cm", sku: "APU-25X10", unit: "40s", price: 280.00 },
            { id: 4, name: "Alcohol Pads/Swabs 65mm x 30mm 70% Isopropyl Alcohol", sku: "ALC-65X30", unit: "100s", price: 360.00 },
            { id: 5, name: "Autoclave Tape 1\" x 50M", sku: "AUT-1IN", unit: "Each Piece", price: 2540.00 },
            { id: 6, name: "Autoclave Tape 1/2\" x 50M", sku: "AUT-0.5IN", unit: "Each Piece", price: 380.00 },
            { id: 7, name: "Autoclave Tape 3/4\" x 50M", sku: "AUT-0.75IN", unit: "Each Piece", price: 110.00 },
            { id: 8, name: "Brain Swabs", sku: "BRA-SWA", unit: "10s", price: 190.00 },
            { id: 9, name: "Cotton Balls (Sterile Packed)", sku: "COT-BAL-ST", unit: "100s", price: 310.00 },
            { id: 10, name: "Cotton Wool - 50Gms", sku: "COT-50G", unit: "Each Piece", price: 60.00 },
            { id: 11, name: "Cotton Wool - 100Gms", sku: "COT-100G", unit: "Each Piece", price: 20.00 },
            { id: 12, name: "Cotton Wool - 200Gms", sku: "COT-200G", unit: "Each Piece", price: 30.00 },
            { id: 13, name: "Cotton Wool - 400Gms", sku: "COT-400G", unit: "Each Piece", price: 40.00 },
            { id: 14, name: "Cotton Wool - 500Gms", sku: "COT-500G", unit: "Each Piece", price: 50.00 },
            { id: 15, name: "Crepe Bandage 2\" x 4.5M", sku: "CRE-2IN", unit: "Each Piece", price: 670.00 },
            { id: 16, name: "Crepe Bandage 3\" x 4.5M", sku: "CRE-3IN", unit: "Each Piece", price: 800.00 },
            { id: 17, name: "Crepe Bandage 4\" x 4.5M", sku: "CRE-4IN", unit: "Each Piece", price: 1270.00 },
            { id: 18, name: "Crepe Bandage 6\" x 4.5M", sku: "CRE-6IN", unit: "Each Piece", price: 1340.00 },
            { id: 19, name: "Eye Pad (Sterile Packed)", sku: "EYE-PAD-ST", unit: "50s", price: 100.00 },
            { id: 20, name: "Gauze Roll 4 Ply 750gms", sku: "GAU-750G", unit: "Each Piece", price: 380.00 },
            { id: 21, name: "Gauze Roll 4 Ply 1.5Kgs (Plain)", sku: "GAU-1.5K-PLN", unit: "Each Piece", price: 190.00 },
            { id: 22, name: "Gauze Roll 4 Ply 1.5Kgs (Xray Detectable)", sku: "GAU-1.5K-XR", unit: "Each Piece", price: 440.00 },
            { id: 23, name: "Gauze Swabs 2'' x 2'' Non-Sterile", sku: "GAS-2X2-NS", unit: "100s", price: 240.00 },
            { id: 24, name: "Gauze Swabs 2'' x 2'' Sterile", sku: "GAS-2X2-ST", unit: "100s", price: 560.00 },
            { id: 25, name: "Gauze Swabs 3'' x 3'' Non-Sterile", sku: "GAS-3X3-NS", unit: "100s", price: 100.00 },
            { id: 26, name: "Gauze Swabs 3'' x 3'' Sterile", sku: "GAS-3X3-ST", unit: "100s", price: 420.00 },
            { id: 27, name: "Gauze Swabs 4'' x 4'' Non-Sterile", sku: "GAS-4X4-NS", unit: "100s", price: 280.00 },
            { id: 28, name: "Gauze Swabs 4'' x 4'' Sterile", sku: "GAS-4X4-ST", unit: "100s", price: 360.00 },
            { id: 29, name: "IV Fixation Dressing Waterproof 7cmx9cm", sku: "IVF-7X9", unit: "50s", price: 1340.00 },
            { id: 30, name: "Laparatomy Sponges Sterile 40cmx40cm", sku: "LAP-40X40", unit: "10s", price: 1070.00 },
            { id: 31, name: "Laparatomy Sponges Sterile 45cmx45cm", sku: "LAP-45X45", unit: "25s", price: 2000.00 },
            { id: 32, name: "Orthopaedic Padding 4''", sku: "ORT-PAD-4", unit: "12s", price: 580.00 },
            { id: 33, name: "Orthopaedic Padding 6''", sku: "ORT-PAD-6", unit: "12s", price: 640.00 },
            { id: 34, name: "Orthopaedic Padding 8''", sku: "ORT-PAD-8", unit: "12s", price: 770.00 },
            { id: 35, name: "Otto-Tulle 10cm*10cm", sku: "OTT-10X10", unit: "10s", price: 470.00 },
            { id: 36, name: "P.O.P China 4\"", sku: "POP-CHN-4", unit: "Each Piece", price: 60.00 },
            { id: 37, name: "P.O.P China 6''", sku: "POP-CHN-6", unit: "Each Piece", price: 70.00 },
            { id: 38, name: "P.O.P China 8''", sku: "POP-CHN-8", unit: "Each Piece", price: 80.00 },
            { id: 39, name: "P.O.P Fiber Glass 3\"", sku: "POP-FGB-3", unit: "Each Piece", price: 470.00 },
            { id: 40, name: "P.O.P Fiber Glass 4\"", sku: "POP-FGB-4", unit: "Each Piece", price: 540.00 },
            { id: 41, name: "P.O.P Fiber Glass 5\"", sku: "POP-FGB-5", unit: "Each Piece", price: 630.00 },
            { id: 42, name: "P.O.P Fiber Glass 6\"", sku: "POP-FGB-6", unit: "Each Piece", price: 710.00 },
            { id: 43, name: "P.O.P Gypsona 4''", sku: "POP-GYP-4", unit: "Each Piece", price: 320.00 },
            { id: 44, name: "P.O.P Gypsona 6''", sku: "POP-GYP-6", unit: "Each Piece", price: 460.00 },
            { id: 45, name: "P.O.P Gypsona 8''", sku: "POP-GYP-8", unit: "Each Piece", price: 550.00 },
            { id: 46, name: "Parafin Gauze 10cm x10cm", sku: "PAR-10X10", unit: "10s", price: 250.00 },
            { id: 47, name: "Prolene Mesh 15*15", sku: "PRO-15X15", unit: "Each Piece", price: 5600.00 },
            { id: 48, name: "Prolene Mesh 6*11", sku: "PRO-6X11", unit: "Each Piece", price: 4000.00 },
            { id: 49, name: "Standard Dressing No. 7", sku: "STD-DRS-7", unit: "Each Piece", price: 40.00 },
            { id: 50, name: "Standard Dressing No. 8", sku: "STD-DRS-8", unit: "Each Piece", price: 50.00 },
            { id: 51, name: "Standard Dressing No. 9", sku: "STD-DRS-9", unit: "Each Piece", price: 60.00 },
            { id: 52, name: "Transpore Tape 1'' x 5yds", sku: "TRA-1X5YD", unit: "12s", price: 640.00 },
            { id: 53, name: "Transpore Tape 2'' x 5yds", sku: "TRA-2X5YD", unit: "12s", price: 1280.00 },
            { id: 54, name: "W.O.W Bandages 2''x 4yds", sku: "WOW-2X4", unit: "12s", price: 80.00 },
            { id: 55, name: "W.O.W Bandages 3''x 4yds", sku: "WOW-3X4", unit: "12s", price: 100.00 },
            { id: 56, name: "W.O.W Bandages 4''x 4yds", sku: "WOW-4X4", unit: "12s", price: 130.00 },
            { id: 57, name: "W.O.W Bandages 6''x 4yds", sku: "WOW-6X4", unit: "12s", price: 180.00 },
            { id: 58, name: "Zinc Oxide Plaster (ZOP) 1'' x 4yds", sku: "ZOP-1X4", unit: "Each Piece", price: 40.00 },
            { id: 59, name: "Zinc Oxide Plaster (ZOP) 2'' x 4yds", sku: "ZOP-2X4", unit: "Each Piece", price: 60.00 },
            { id: 60, name: "Zinc Oxide Plaster (ZOP) 3'' x 4yds", sku: "ZOP-3X4", unit: "Each Piece", price: 90.00 },
            { id: 61, name: "Zinc Oxide Plaster (ZOP) 4'' x 4yds", sku: "ZOP-4X4", unit: "Each Piece", price: 100.00 },
            { id: 62, name: "Zinc Oxide Plaster (ZOP) 6'' x 4yds", sku: "ZOP-6X4", unit: "Each Piece", price: 180.00 }
        ]
    },
    gloves: {
        name: "Gloves",
        description: "Protective medical gloves for all healthcare procedures",
        image: "gloves.png",
        icon: "fa-hand-holding",
        products: [
            { id: 1, name: "Gynaecological Gloves Powder-Free 7.5", sku: "GYN-PF-7.5", unit: "Each Pair", price: 110.00 },
            { id: 2, name: "Gynaecological Gloves Pwd - 7.5 Medium", sku: "GYN-PW-7.5M", unit: "Each Pair", price: 80.00 },
            { id: 3, name: "Latex Examination Gloves Pre-Powdered Large", sku: "LAT-PP-L", unit: "100s", price: 380.00 },
            { id: 4, name: "Latex Examination Gloves Pre-Powdered Medium", sku: "LAT-PP-M", unit: "100s", price: 350.00 },
            { id: 5, name: "Latex Examination Gloves Pre-Powdered Small", sku: "LAT-PP-S", unit: "100s", price: 350.00 },
            { id: 6, name: "Latex Examination Non-Powdered Gloves Large", sku: "LAT-NP-L", unit: "100s", price: 450.00 },
            { id: 7, name: "Latex Examination Non-Powdered Gloves Medium", sku: "LAT-NP-M", unit: "100s", price: 470.00 },
            { id: 8, name: "Latex Examination Non-Powdered Gloves Small", sku: "LAT-NP-S", unit: "100s", price: 450.00 },
            { id: 9, name: "Nitrile Examination Gloves Powder-Free Large", sku: "NIT-PF-L", unit: "100s", price: 410.00 },
            { id: 10, name: "Nitrile Examination Gloves Powder-Free Medium", sku: "NIT-PF-M", unit: "100s", price: 410.00 },
            { id: 11, name: "Nitrile Examination Gloves Powder-Free Small", sku: "NIT-PF-S", unit: "100s", price: 410.00 },
            { id: 12, name: "Plastic (PE) Gloves Large", sku: "PLA-PE-L", unit: "100s", price: 60.00 },
            { id: 13, name: "Plastic (PE) Gloves Medium", sku: "PLA-PE-M", unit: "100s", price: 60.00 },
            { id: 14, name: "Surgical Gloves Powder-Free 6.0", sku: "SUR-PF-6.0", unit: "50pairs", price: 1990.00 },
            { id: 15, name: "Surgical Gloves Powder-Free 6.5", sku: "SUR-PF-6.5", unit: "50pairs", price: 1690.00 },
            { id: 16, name: "Surgical Gloves Powder-Free 7.0", sku: "SUR-PF-7.0", unit: "50pairs", price: 1690.00 },
            { id: 17, name: "Surgical Gloves Powder-Free 7.5", sku: "SUR-PF-7.5", unit: "50pairs", price: 1690.00 },
            { id: 18, name: "Surgical Gloves Powder-Free 8.0", sku: "SUR-PF-8.0", unit: "50pairs", price: 1990.00 },
            { id: 19, name: "Surgical Gloves PP 6.5", sku: "SUR-PP-6.5", unit: "50pairs", price: 1020.00 },
            { id: 20, name: "Surgical Gloves PP 7.0", sku: "SUR-PP-7.0", unit: "50pairs", price: 1020.00 },
            { id: 21, name: "Surgical Gloves PP 7.5", sku: "SUR-PP-7.5", unit: "50pairs", price: 1020.00 },
            { id: 22, name: "Surgical Gloves PP 8.0", sku: "SUR-PP-8.0", unit: "50pairs", price: 1020.00 }
        ]
    },
    sutures: {
        name: "Sutures and Blades",
        description: "Premium surgical sutures and sterile surgical blades",
        image: "sutures.png",
        icon: "fa-cut",
        products: [
            { id: 1, name: "Chromic Catgut Sutures 2/0 RB", sku: "CHR-2-0-RB", unit: "12s", price: 480.00 },
            { id: 2, name: "Chromic Catgut Sutures 1 RB", sku: "CHR-1-RB", unit: "12s", price: 480.00 },
            { id: 3, name: "Chromic Catgut Sutures 1 RC", sku: "CHR-1-RC", unit: "12s", price: 480.00 },
            { id: 4, name: "Chromic Catgut Sutures 2 RB", sku: "CHR-2-RB", unit: "12s", price: 480.00 },
            { id: 5, name: "Chromic Catgut Sutures 2 RC", sku: "CHR-2-RC", unit: "12s", price: 480.00 },
            { id: 6, name: "Chromic Catgut Sutures 2/0 RC", sku: "CHR-2-0-RC", unit: "12s", price: 480.00 },
            { id: 7, name: "Chromic Catgut Sutures 3 RB", sku: "CHR-3-RB", unit: "12s", price: 480.00 },
            { id: 8, name: "Chromic Catgut Sutures 3 RC", sku: "CHR-3-RC", unit: "12s", price: 480.00 },
            { id: 9, name: "Chromic Catgut Sutures 3/0 RB", sku: "CHR-3-0-RB", unit: "12s", price: 480.00 },
            { id: 10, name: "Chromic Catgut Sutures 3/0 RC", sku: "CHR-3-0-RC", unit: "12s", price: 480.00 },
            { id: 11, name: "Chromic Catgut Sutures 4/0 RB", sku: "CHR-4-0-RB", unit: "12s", price: 480.00 },
            { id: 12, name: "Chromic Catgut Sutures 4/0 RC", sku: "CHR-4-0-RC", unit: "12s", price: 480.00 },
            { id: 13, name: "Chromic Catgut Sutures 4 RB", sku: "CHR-4-RB", unit: "12s", price: 480.00 },
            { id: 14, name: "Chromic Catgut Sutures 4 RC", sku: "CHR-4-RC", unit: "12s", price: 480.00 },
            { id: 15, name: "Monocyrl 2/0 RC", sku: "MON-2-0-RC", unit: "12s", price: 3840.00 },
            { id: 16, name: "Monocyrl 3/0 RC", sku: "MON-3-0-RC", unit: "12s", price: 3840.00 },
            { id: 17, name: "Nylon Monofilament Suture 1 RB", sku: "NYL-1-RB", unit: "12s", price: 300.00 },
            { id: 18, name: "Nylon Monofilament Suture 1 RC", sku: "NYL-1-RC", unit: "12s", price: 300.00 },
            { id: 19, name: "Nylon Monofilament Suture 2 RB", sku: "NYL-2-RB", unit: "12s", price: 300.00 },
            { id: 20, name: "Nylon Monofilament Suture 2 RC", sku: "NYL-2-RC", unit: "12s", price: 300.00 },
            { id: 21, name: "Nylon Monofilament Suture 2/0 RB", sku: "NYL-2-0-RB", unit: "12s", price: 300.00 },
            { id: 22, name: "Nylon Monofilament Suture 2/0 RC", sku: "NYL-2-0-RC", unit: "12s", price: 300.00 },
            { id: 23, name: "Nylon Monofilament Suture 3 RB", sku: "NYL-3-RB", unit: "12s", price: 300.00 },
            { id: 24, name: "Nylon Monofilament Suture 3 RC", sku: "NYL-3-RC", unit: "12s", price: 300.00 },
            { id: 25, name: "Nylon Monofilament Suture 3/0 RB", sku: "NYL-3-0-RB", unit: "12s", price: 300.00 },
            { id: 26, name: "Nylon Monofilament Suture 3/0 RC", sku: "NYL-3-0-RC", unit: "12s", price: 300.00 },
            { id: 27, name: "Nylon Monofilament Suture 4/0 RB", sku: "NYL-4-0-RB", unit: "12s", price: 300.00 },
            { id: 28, name: "Nylon Monofilament Suture 4/0 RC", sku: "NYL-4-0-RC", unit: "12s", price: 300.00 },
            { id: 29, name: "Nylon Monofilament Suture 4 RB", sku: "NYL-4-RB", unit: "12s", price: 300.00 },
            { id: 30, name: "Nylon Monofilament Suture 4 RC", sku: "NYL-4-RC", unit: "12s", price: 300.00 },
            { id: 31, name: "Polyglactin Suture 0 RB", sku: "POL-0-RB", unit: "12s", price: 900.00 },
            { id: 32, name: "Polyglactin Suture 0 RC", sku: "POL-0-RC", unit: "12s", price: 900.00 },
            { id: 33, name: "Polyglactin Suture 1 RB", sku: "POL-1-RB", unit: "12s", price: 900.00 },
            { id: 34, name: "Polyglactin Suture 1 RC", sku: "POL-1-RC", unit: "12s", price: 900.00 },
            { id: 35, name: "Polyglactin Suture 2 RB", sku: "POL-2-RB", unit: "12s", price: 900.00 },
            { id: 36, name: "Polyglactin Suture 2 RC", sku: "POL-2-RC", unit: "12s", price: 900.00 },
            { id: 37, name: "Polyglactin Suture 2/0 RB", sku: "POL-2-0-RB", unit: "12s", price: 900.00 },
            { id: 38, name: "Polyglactin Suture 2/0 RC", sku: "POL-2-0-RC", unit: "12s", price: 900.00 },
            { id: 39, name: "Polyglactin Suture 3 RB", sku: "POL-3-RB", unit: "12s", price: 900.00 },
            { id: 40, name: "Polyglactin Suture 3 RC", sku: "POL-3-RC", unit: "12s", price: 900.00 },
            { id: 41, name: "Polyglactin Suture 3/0 RB", sku: "POL-3-0-RB", unit: "12s", price: 900.00 },
            { id: 42, name: "Polyglactin Suture 3/0 RC", sku: "POL-3-0-RC", unit: "12s", price: 900.00 },
            { id: 43, name: "Polyglactin Suture 4/0 RB", sku: "POL-4-0-RB", unit: "12s", price: 900.00 },
            { id: 44, name: "Polyglactin Suture 4/0 RC", sku: "POL-4-0-RC", unit: "12s", price: 900.00 },
            { id: 45, name: "Silk 2 RB 90cm 1/2 Circle 40mm Braided", sku: "SIL-2-RB-90", unit: "12s", price: 360.00 },
            { id: 46, name: "Surgical Blade Sz. 20", sku: "BLA-20", unit: "100s", price: 500.00 },
            { id: 47, name: "Surgical Blade Sz. 21", sku: "BLA-21", unit: "100s", price: 500.00 },
            { id: 48, name: "Surgical Blade Sz. 22", sku: "BLA-22", unit: "100s", price: 500.00 },
            { id: 49, name: "Surgical Blade Sz. 10", sku: "BLA-10", unit: "100s", price: 500.00 },
            { id: 50, name: "Surgical Blade Sz. 11", sku: "BLA-11", unit: "100s", price: 500.00 },
            { id: 51, name: "Surgical Blade Sz. 12", sku: "BLA-12", unit: "100s", price: 500.00 },
            { id: 52, name: "Surgical Blade Sz. 15", sku: "BLA-15", unit: "100s", price: 500.00 },
            { id: 53, name: "Surgical Blade Sz. 15 with Handle", sku: "BLA-15-H", unit: "10s", price: 280.00 },
            { id: 54, name: "Surgical Blade Sz. 23", sku: "BLA-23", unit: "100s", price: 500.00 },
            { id: 55, name: "Surgical Blade Sz. 23 with Handle", sku: "BLA-23-H", unit: "10s", price: 280.00 },
            { id: 56, name: "Surgical Blade Sz. 24", sku: "BLA-24", unit: "100s", price: 500.00 }
        ]
    },
    linen: {
        name: "Hospital Linen",
        description: "Quality hospital linen and patient care supplies",
        image: "linen.png",
        icon: "fa-sheets-bed",
        products: [
            { id: 1, name: "Adult Diapers Large", sku: "ADI-L", unit: "10s", price: 800.00 },
            { id: 2, name: "Adult Diapers Medium", sku: "ADI-M", unit: "10s", price: 800.00 },
            { id: 3, name: "Adult Diapers X-Large", sku: "ADI-XL", unit: "10s", price: 800.00 },
            { id: 4, name: "Clinelle Wet Wipes", sku: "CLI-WIP", unit: "200s", price: 1870.00 },
            { id: 5, name: "Disposable Aprons (Green-Heavy Duty)", sku: "APR-GRN-HD", unit: "100s", price: 2800.00 },
            { id: 6, name: "Disposable Aprons (White)", sku: "APR-WHT", unit: "100s", price: 740.00 },
            { id: 7, name: "Disposable Aprons (Blue-Heavy Duty)", sku: "APR-BLU-HD", unit: "10s", price: 1320.00 },
            { id: 8, name: "Disposable Cesarean Drape (160/230*305cm)", sku: "CES-DRP", unit: "Each Piece", price: 1410.00 },
            { id: 9, name: "Disposable Cesarean Kit", sku: "CES-KIT", unit: "Each Piece", price: 2120.00 },
            { id: 10, name: "Disposable Delivery Drape", sku: "DEL-DRP", unit: "Each Piece", price: 470.00 },
            { id: 11, name: "Disposable Delivery Kit", sku: "DEL-KIT", unit: "Each Piece", price: 1410.00 },
            { id: 12, name: "Disposable Sterile Surgical Gown - Reinforced (with hand towels) M,L,XL,XXL", sku: "SGN-RFI-HT", unit: "Each Piece", price: 360.00 },
            { id: 13, name: "Disposable Sterile Surgical Gown - Reinforced (without hand towels) PE Pack M,L,XL", sku: "SGN-RFI-NO", unit: "Each Piece", price: 250.00 },
            { id: 14, name: "Disposable Sterile Surgical Gown - Standard (without hand towels) L,XL", sku: "SGN-STD-NO", unit: "Each Piece", price: 180.00 },
            { id: 15, name: "Disposable Sterile Surgical Gown - Fully Reinforced (with hand towels) XL", sku: "SGN-FUL-HT", unit: "Each Piece", price: 390.00 },
            { id: 16, name: "Disposable Surgical Gown-PE /Semi PE Coating L/XL", sku: "SGN-PE-COT", unit: "10s", price: 1200.00 },
            { id: 17, name: "Doctors Caps, Blue Color with Ties", sku: "CAP-DOC-BLU", unit: "100s", price: 640.00 },
            { id: 18, name: "Dressing Pad/Underpad 180x90cm", sku: "DRS-PAD-180", unit: "20s", price: 2640.00 },
            { id: 19, name: "Dressing Pad/Underpad 60x90cm", sku: "DRS-PAD-60", unit: "10s", price: 540.00 },
            { id: 20, name: "Maternity/Sanitary Pads", sku: "MAT-PAD", unit: "10s", price: 100.00 },
            { id: 21, name: "Medical Facemasks with Loop 3ply (Blue)", sku: "MAS-LOOP", unit: "50s", price: 200.00 },
            { id: 22, name: "Medical Facemasks with Ties 3ply (Blue)", sku: "MAS-TIES", unit: "50s", price: 230.00 },
            { id: 23, name: "Medical Shoe Covers Non-Woven Type (High Quality)", sku: "SHO-NWV", unit: "100s", price: 430.00 },
            { id: 24, name: "Medical Shoe Covers PE Type (High Quality)", sku: "SHO-PE", unit: "100s", price: 280.00 },
            { id: 25, name: "Medispread", sku: "MED-SPR", unit: "42s", price: 400.00 },
            { id: 26, name: "Nurses Caps/Non-Woven Mob Cap (Blue/White/Green)", sku: "CAP-NRS", unit: "100s", price: 260.00 },
            { id: 27, name: "Protective Coverall Suits (Medium/Large/X-Large)", sku: "COV-SUIT", unit: "Each Piece", price: 840.00 },
            { id: 28, name: "Surgical Drape Sterile with Adhesive 240x150cm Type 2", sku: "SGN-DRP-ADH", unit: "Each Piece", price: 350.00 },
            { id: 29, name: "Surgical Sterile Facemasks with Loop 3ply (Blue)", sku: "SUR-MAS-LOOP", unit: "50s", price: 380.00 },
            { id: 30, name: "Surgical Sterile Facemasks with Ties 3ply (Blue)", sku: "SUR-MAS-TIES", unit: "50s", price: 440.00 }
        ]
    },
    catheters: {
        name: "Catheters and Tubes/Airway Management",
        description: "Complete range of catheters, tubes, and airway management devices",
        image: "catheters.png",
        icon: "fa-lungs",
        products: [
            { id: 1, name: "Anaesthetic Mask PVC #0", sku: "ANS-MAS-0", unit: "Each Piece", price: 290.00 },
            { id: 2, name: "Anaesthetic Mask PVC #1,2,3,4,5", sku: "ANS-MAS-12345", unit: "Each Piece", price: 240.00 },
            { id: 3, name: "Anaesthetic Mask SILICONE Round Type #0,1,2 Bending Edge #3, 4 , 5", sku: "ANS-MAS-SIL", unit: "Each Piece", price: 2140.00 },
            { id: 4, name: "Bacterial Filters (Breathing Filters) Adult/Paediatric", sku: "BAC-FIL", unit: "Each Piece", price: 140.00 },
            { id: 5, name: "Blood Collection Bag-450 ml Single CPDA-1", sku: "BLD-COL-450", unit: "Each Piece", price: 240.00 },
            { id: 6, name: "Blood Giving Set Vented", sku: "BLD-GIV-VEN", unit: "25s", price: 670.00 },
            { id: 7, name: "Bougie (Endotracheal Tube Introducer) Fr 6,10,15", sku: "BOU-ETI", unit: "Each Piece", price: 1470.00 },
            { id: 8, name: "Breathing Bag 0.5,1,2,3 Ltrs", sku: "BRT-BAG", unit: "Each Piece", price: 470.00 },
            { id: 9, name: "Breathing Respirometer 800ml", sku: "BRT-RES", unit: "Each Piece", price: 1600.00 },
            { id: 10, name: "Catheter Mounts Double Swivel Elbow 15f/22m", sku: "CAT-MOU", unit: "Each Piece", price: 120.00 },
            { id: 11, name: "Chest Drainage Bottle China", sku: "CHT-DRN-CHN", unit: "Each Piece", price: 1340.00 },
            { id: 12, name: "Chest Drainage Bottle India", sku: "CHT-DRN-IND", unit: "Each Piece", price: 2400.00 },
            { id: 13, name: "Chest Drainage Tubes with Trocar Sz 8,10,12,14,16/18/20/22/24/26/28/30/32/36", sku: "CHT-TUB-TRCR", unit: "Each Piece", price: 510.00 },
            { id: 14, name: "Chest Drainage Tubes WITHOUT Trocar Sz 16/ 18/20 /22 /24/26/28/30/32", sku: "CHT-TUB-NO-TRCR", unit: "Each Piece", price: 510.00 },
            { id: 15, name: "Closed Suction Catheters F8,F10,F12,F14", sku: "CLS-SUC-CAT", unit: "Each Piece", price: 910.00 },
            { id: 16, name: "Colostomy Bag Two-Piece Adult (Disposable)", sku: "COL-BAG-2PA", unit: "10s", price: 560.00 },
            { id: 17, name: "Colostomy Bag Two-Piece Child (Disposable)", sku: "COL-BAG-2PC", unit: "10s", price: 560.00 },
            { id: 18, name: "Colostomy Bags One Piece 60/70mm", sku: "COL-BAG-1P", unit: "Each Piece", price: 470.00 },
            { id: 19, name: "Colostomy Bags Two Piece 70mm", sku: "COL-BAG-2P70", unit: "Each Piece", price: 480.00 },
            { id: 20, name: "Colostomy Barrier Two-Piece Type 70mm", sku: "COL-BAR", unit: "Each Piece", price: 510.00 },
            { id: 21, name: "Disposable Breathing Circuit Adult Reinforced 1.2M and 1.6M", sku: "DBR-CIR-1.2-1.6", unit: "Each Piece", price: 800.00 },
            { id: 22, name: "Disposable Breathing Circuit Adult Reinforced 1.2M with Water Traps", sku: "DBR-CIR-1.2-WT", unit: "Each Piece", price: 1600.00 },
            { id: 23, name: "Disposable Breathing Circuit Adult Reinforced 1.6M with Water Traps", sku: "DBR-CIR-1.6-WT", unit: "Each Piece", price: 1600.00 },
            { id: 24, name: "Disposable Breathing Circuit Extendable, Adult 1.6M", sku: "DBR-CIR-EXT-1.6", unit: "Each Piece", price: 620.00 },
            { id: 25, name: "Disposable Breathing Circuit Extendable, Adult 2M", sku: "DBR-CIR-EXT-2", unit: "Each Piece", price: 670.00 },
            { id: 26, name: "Disposable Breathing Circuit Extendable, Child 1.2M,2M", sku: "DBR-CIR-EXT-CHD", unit: "Each Piece", price: 670.00 },
            { id: 27, name: "Double Barrel (Inner Cannula) Tracheostomy Tubes Cuffed Fr 5,6,7,8", sku: "DOU-BAR-TRCH", unit: "Each Piece", price: 5580.00 },
            { id: 28, name: "ECG Electrodes HS02 Solid Gel 37x42mm (M/S/L)", sku: "ECG-ELC-HS02", unit: "50s", price: 500.00 },
            { id: 29, name: "ECG Electrodes HS11 Solid Gel 50x55mm (M/ICU/CCU/S/E/L)", sku: "ECG-ELC-HS11", unit: "50s", price: 500.00 },
            { id: 30, name: "ECG Electrodes Neutral HG01 Monopolar 210x100mm", sku: "ECG-ELC-HG01", unit: "Each Piece", price: 190.00 }
        ]
    },
    dialysis: {
        name: "Dialysis Products",
        description: "Specialized dialysis supplies and equipment",
        image: "dialysis.png",
        icon: "fa-droplet",
        products: [
            { id: 1, name: "AV Fistula Needle G15/G16/G17*26MM", sku: "AVF-NEE-26", unit: "Each Piece", price: 60.00 },
            { id: 2, name: "Bloodlines for Dialysis", sku: "BLD-DIAL", unit: "Each Piece", price: 520.00 },
            { id: 3, name: "Dialyzer 1.8H/2.0H Polyethersulfone", sku: "DIL-1.8-2.0", unit: "Each Piece", price: 1470.00 },
            { id: 4, name: "Disposable Hemodialysis Catheter Kit Double Lumen 11.5Frx15cm", sku: "HMD-CAT-15", unit: "Each Kit", price: 3470.00 },
            { id: 5, name: "Disposable Hemodialysis Catheter Kit Double Lumen 11.5Frx20cm", sku: "HMD-CAT-20", unit: "Each Kit", price: 3470.00 }
        ]
    },
    vascular: {
        name: "Vascular Access",
        description: "Central venous and vascular access devices",
        image: "vascular.png",
        icon: "fa-hand-holding-droplet",
        products: [
            { id: 1, name: "CVC Mini-Kit 7fr x20cm Tripple Lumen Without Dressing Adult", sku: "CVC-MN-7-NDD", unit: "Each Kit", price: 1940.00 },
            { id: 2, name: "CVC Kits 7fr x20cm Tripple Lumen with Dressing Adult", sku: "CVC-7-3L-DD", unit: "Each Kit", price: 3740.00 },
            { id: 3, name: "CVC Kits 7fr x20cm Double Lumen with Dressing Adult", sku: "CVC-7-2L-DD", unit: "Each Kit", price: 2670.00 },
            { id: 4, name: "CVC Kits 5.5fr x13cm Tripple Lumen with Dressing Peadiatric", sku: "CVC-5.5-3L-PED", unit: "Each Kit", price: 3870.00 },
            { id: 5, name: "CVC Kits 5fr x13cm Double Lumen with Dressing Peadiatric", sku: "CVC-5-2L-PED", unit: "Each Kit", price: 2800.00 },
            { id: 6, name: "CVC Kits 4fr x 8cm Tripple Lumen with Dressing Infant", sku: "CVC-4-3L-INF", unit: "Each Kit", price: 5070.00 },
            { id: 7, name: "CVC Kits 4fr x 8cm Tripple Lumen Without Dressing Infant", sku: "CVC-4-3L-NDD-INF", unit: "Each Kit", price: 3740.00 },
            { id: 8, name: "CVC Kits 4fr x 5cm Tripple with Dressing Neonatal", sku: "CVC-4-3L-NEO", unit: "Each Kit", price: 5070.00 },
            { id: 9, name: "Disposable Pressure Transducer Single-DPI 248", sku: "DIS-PRE-TRN", unit: "Each Piece", price: 2670.00 }
        ]
    },
    "iv-fluids": {
        name: "IV Fluids",
        description: "Intravenous fluids and medications",
        image: "instruments.png",
        icon: "fa-flask",
        products: [
            { id: 1, name: "Dextrose 10% 500ml", sku: "DEX-10-500", unit: "Each Vial", price: 90.00 },
            { id: 2, name: "Dextrose 5% 500ml", sku: "DEX-5-500", unit: "Each Vial", price: 70.00 },
            { id: 3, name: "Dextrose 5% In Normal Saline(DNS) 500ml", sku: "DNS-500", unit: "Each Vial", price: 90.00 },
            { id: 4, name: "Dextrose 50% 100ml", sku: "DEX-50-100", unit: "Each Vial", price: 110.00 },
            { id: 5, name: "Esomeprazole IV", sku: "ESO-IV", unit: "Each Vial", price: 110.00 },
            { id: 6, name: "Flucloxacillin IV", sku: "FLU-IV", unit: "Each Vial", price: 50.00 },
            { id: 7, name: "Fluconazole IV", sku: "FLU-FLU-IV", unit: "Each Vial", price: 200.00 },
            { id: 8, name: "Hartmanns Solution 500ml", sku: "HAR-500", unit: "Each Vial", price: 90.00 },
            { id: 9, name: "Metronidazole IV", sku: "MET-IV", unit: "Each Vial", price: 50.00 },
            { id: 10, name: "Normal Saline 500ml", sku: "NOR-SAL-500", unit: "Each Vial", price: 90.00 },
            { id: 11, name: "Ondasentron IV 100ml", sku: "OND-IV-100", unit: "Each Vial", price: 110.00 },
            { id: 12, name: "Paracetamol IV 100ml", sku: "PAR-IV-100", unit: "Each Vial", price: 100.00 },
            { id: 13, name: "Water For Injection 10ml", sku: "WAT-INJ-10", unit: "50s", price: 260.00 }
        ]
    },
    cleaning: {
        name: "Cleaning Appliances",
        description: "Hospital-grade cleaning and sterilization solutions",
        image: "instruments.png",
        icon: "fa-bottle",
        products: [
            { id: 1, name: "Laundry Chlorine Bleach 20Kgs", sku: "LAU-CHL-20K", unit: "Each Bottle", price: 7500.00 },
            { id: 2, name: "Degreaser Heavy Duty 20Liters", sku: "DEG-HD-20L", unit: "Each Bottle", price: 2500.00 },
            { id: 3, name: "Laundry Oxygen Bleach 20Liters", sku: "LAU-OXY-20L", unit: "Each Bottle", price: 4700.00 },
            { id: 4, name: "Laundry Booster 20Liters", sku: "LAU-BOS-20L", unit: "Each Bottle", price: 4400.00 },
            { id: 5, name: "Hand Washing Gel (Antibacterial) 20Liters", sku: "HAD-GEL-20L", unit: "Each Bottle", price: 2500.00 },
            { id: 6, name: "Multipurpose Liquid Detergent 20Liters", sku: "MUL-DET-20L", unit: "Each Bottle", price: 1400.00 }
        ]
    },
    appliances: {
        name: "Other Appliances",
        description: "General appliances and consumables",
        image: "instruments.png",
        icon: "fa-vial",
        products: [
            { id: 1, name: "Aquious Cream 500grams", sku: "AQU-CRE-500", unit: "Each Packet", price: 200.00 },
            { id: 2, name: "Emulsifying Cream 500grams", sku: "EMU-CRE-500", unit: "Each Packet", price: 400.00 },
            { id: 3, name: "GV Powder 25gms", sku: "GVP-25", unit: "Each Packet", price: 100.00 },
            { id: 4, name: "GV Crystal 25gms", sku: "GVC-25", unit: "Each Packet", price: 200.00 },
            { id: 5, name: "Medicinal Boric Acid 500gms", sku: "MED-BOR-500", unit: "Each Packet", price: 300.00 }
        ]
    },
    surgical: {
        name: "Surgical Instruments",
        description: "Professional-grade surgical and medical instruments",
        image: "instruments.png",
        icon: "fa-syringe",
        products: [
            { id: 1, name: "Artery Forcep 6\" Curved", sku: "ART-6-CRV", unit: "Each Piece", price: 540.00 },
            { id: 2, name: "Artery Forcep 6\" Straight", sku: "ART-6-STR", unit: "Each Piece", price: 540.00 },
            { id: 3, name: "Artery Forcep 7\" Curved", sku: "ART-7-CRV", unit: "Each Piece", price: 940.00 },
            { id: 4, name: "Artery Forcep 7\" Straight", sku: "ART-7-STR", unit: "Each Piece", price: 940.00 },
            { id: 5, name: "Backhaus Towel Clamp", sku: "BAC-TOW", unit: "Each Piece", price: 470.00 },
            { id: 6, name: "Blade Holder Number 3\"", sku: "BLA-HOL-3", unit: "Each Piece", price: 400.00 },
            { id: 7, name: "Blade Holder Number 4\"", sku: "BLA-HOL-4", unit: "Each Piece", price: 400.00 },
            { id: 8, name: "Chetale Forceps 10\"", sku: "CHE-FOR-10", unit: "Each Piece", price: 940.00 },
            { id: 9, name: "Crocodile Forceps 10\"", sku: "CRO-FOR-10", unit: "Each Piece", price: 2670.00 },
            { id: 10, name: "Crocodile Forceps 7\"", sku: "CRO-FOR-7", unit: "Each Piece", price: 2400.00 },
            { id: 11, name: "Toothed Dissecting Forceps 5\"", sku: "TOO-DIS-5", unit: "Each Piece", price: 400.00 },
            { id: 12, name: "Toothed Dissecting Forceps 6\"", sku: "TOO-DIS-6", unit: "Each Piece", price: 400.00 },
            { id: 13, name: "Toothed Dissecting Forceps 7\"", sku: "TOO-DIS-7", unit: "Each Piece", price: 400.00 },
            { id: 14, name: "Toothed Dissecting Forceps 8\"", sku: "TOO-DIS-8", unit: "Each Piece", price: 400.00 },
            { id: 15, name: "Plain Dissecting Forceps 5\"", sku: "PLA-DIS-5", unit: "Each Piece", price: 400.00 },
            { id: 16, name: "Plain Dissecting Forceps 6\"", sku: "PLA-DIS-6", unit: "Each Piece", price: 400.00 },
            { id: 17, name: "Plain Dissecting Forceps 7\"", sku: "PLA-DIS-7", unit: "Each Piece", price: 400.00 },
            { id: 18, name: "Plain Dissecting Forceps 8\"", sku: "PLA-DIS-8", unit: "Each Piece", price: 400.00 },
            { id: 19, name: "Dressing Drum 11*9", sku: "DRS-DRM-11X9", unit: "Each Piece", price: 2400.00 },
            { id: 20, name: "Dressing Drum 14*10", sku: "DRS-DRM-14X10", unit: "Each Piece", price: 3340.00 },
            { id: 21, name: "Dressing Drum 9*9", sku: "DRS-DRM-9X9", unit: "Each Piece", price: 2000.00 },
            { id: 22, name: "Dressing Forceps 6\"", sku: "DRS-FOR-6", unit: "Each Piece", price: 540.00 },
            { id: 23, name: "Dressing Set", sku: "DRS-SET", unit: "Each Set", price: 7340.00 },
            { id: 24, name: "Ear Syringe Metal", sku: "EAR-SYR-MET", unit: "Each Piece", price: 2000.00 },
            { id: 25, name: "Ear Syringe Rubber", sku: "EAR-SYR-RUB", unit: "Each Piece", price: 540.00 },
            { id: 26, name: "Episiotomy Scissors 7\"", sku: "EPI-SCI-7", unit: "Each Piece", price: 870.00 },
            { id: 27, name: "Gallipot Large", sku: "GAL-LRG", unit: "Each Piece", price: 400.00 },
            { id: 28, name: "Gallipot Medium", sku: "GAL-MED", unit: "Each Piece", price: 340.00 },
            { id: 29, name: "General Set Minor", sku: "GEN-SET-MN", unit: "Each Set", price: 19340.00 },
            { id: 30, name: "Gigli Saw Wire 50cm", sku: "GIG-SAW-50", unit: "Each Piece", price: 1340.00 }
        ]
    },
    consumables: {
        name: "General Consumables",
        description: "Essential general medical consumables",
        image: "instruments.png",
        icon: "fa-boxes",
        products: [
            { id: 1, name: "Bin Liners (Black,Yellow and Red)", sku: "BIN-LIN", unit: "100s", price: 2400.00 },
            { id: 2, name: "Blood Lancets", sku: "BLD-LAN", unit: "50s", price: 70.00 },
            { id: 3, name: "Bone Marrow Puncture Kit 16G", sku: "BON-MAR-16G", unit: "Each Kit", price: 1320.00 },
            { id: 4, name: "Bulb Sucker", sku: "BUL-SUC", unit: "Each Piece", price: 550.00 },
            { id: 5, name: "Caustic Pencil 40% (Red)", sku: "CAU-PEN-40", unit: "Each Piece", price: 430.00 },
            { id: 6, name: "Caustic Pencil 95% (Blue)", sku: "CAU-PEN-95", unit: "Each Piece", price: 300.00 },
            { id: 7, name: "Cord Clamp (White)", sku: "COR-CLA-WHT", unit: "100s", price: 740.00 },
            { id: 8, name: "Cord Clamps (Blue)", sku: "COR-CLA-BLU", unit: "100s", price: 740.00 },
            { id: 9, name: "Dispensing Bottles 60ml", sku: "DIS-BOT-60", unit: "Each Piece", price: 20.00 },
            { id: 10, name: "Disposable Body Bag", sku: "DIS-BOD-BAG", unit: "Each Piece", price: 3340.00 },
            { id: 11, name: "Disposable Dressing Set", sku: "DIS-DRS-SET", unit: "Each Set", price: 340.00 },
            { id: 12, name: "Disposable Skin Stapler", sku: "DIS-SKN-STA", unit: "Each Piece", price: 2670.00 },
            { id: 13, name: "Disposable Vaginal Speculum M and L", sku: "DIS-VAG-SPEC", unit: "Each Piece", price: 50.00 },
            { id: 14, name: "Enema Kit Douche", sku: "ENE-KIT-DOU", unit: "Each Kit", price: 2000.00 },
            { id: 15, name: "Epidural Kit (Anesthesia Kit AS-E with Dressing) 18G/16G", sku: "EPI-KIT-DD", unit: "Each Kit", price: 810.00 },
            { id: 16, name: "Epidural Kit (Anesthesia Kit AS-E without Dressing) 18G/16G", sku: "EPI-KIT-ND", unit: "Each Kit", price: 1600.00 },
            { id: 17, name: "Fetoscope Metal", sku: "FET-SCOP-MET", unit: "Each Piece", price: 340.00 },
            { id: 18, name: "Fetoscope Plastic", sku: "FET-SCOP-PLA", unit: "Each Piece", price: 340.00 },
            { id: 19, name: "HPylori AG Test Strips", sku: "HPY-AG-TEST", unit: "Each Packet", price: 2400.00 },
            { id: 20, name: "HCT 2 Test Strips", sku: "HCT-2-TEST", unit: "Each Packet", price: 1070.00 },
            { id: 21, name: "SAT AG Test Strips", sku: "SAT-AG-TEST", unit: "Each Packet", price: 2670.00 },
            { id: 22, name: "SAT AB Test Strips", sku: "SAT-AB-TEST", unit: "Each Packet", price: 2400.00 },
            { id: 23, name: "Hepatitis B Test Strips", sku: "HEP-B-TEST", unit: "Each Packet", price: 1070.00 },
            { id: 24, name: "VDRL Test Strips", sku: "VDR-TEST", unit: "Each Packet", price: 1270.00 },
            { id: 25, name: "Hot & Cold Pack", sku: "HOT-CLD-PAC", unit: "Each Packet", price: 600.00 },
            { id: 26, name: "Hot Water Bag Plain", sku: "HOT-WAT-BAG-PLN", unit: "Each Piece", price: 440.00 },
            { id: 27, name: "Hot Water Bag With Cover", sku: "HOT-WAT-BAG-COV", unit: "Each Piece", price: 540.00 },
            { id: 28, name: "Huber Needle G20X20m (Special Needle for Implantable Drug Delivery)", sku: "HUB-NEE-G20", unit: "Each Piece", price: 400.00 }
        ]
    },
    equipment: {
        name: "Hospital Equipment",
        description: "Advanced hospital medical equipment and devices",
        image: "instruments.png",
        icon: "fa-microchip",
        products: [
            { id: 1, name: "Autoclave Machine 18liters", sku: "AUT-MAC-18L", unit: "Each Machine", price: 22500.00 },
            { id: 2, name: "Bathroom Scale Digital", sku: "BAT-SCA-DIG", unit: "Each Scale", price: 6000.00 },
            { id: 3, name: "Bathroom Scale Manual", sku: "BAT-SCA-MAN", unit: "Each Scale", price: 1600.00 },
            { id: 4, name: "BiPAP Ventmed Machine", sku: "BIP-VEN-MAC", unit: "Each Machine", price: 106250.00 },
            { id: 5, name: "BP Machine Aneroid", sku: "BPM-ANE", unit: "Each Machine", price: 1200.00 },
            { id: 6, name: "BP Machine Omron M1 Basic", sku: "BPM-ORM-M1", unit: "Each Machine", price: 4380.00 },
            { id: 7, name: "BP Machine Omron M2 Basic", sku: "BPM-ORM-M2", unit: "Each Machine", price: 5750.00 },
            { id: 8, name: "BP Machine Omron M3", sku: "BPM-ORM-M3", unit: "Each Machine", price: 10630.00 },
            { id: 9, name: "Breast Pump Manual", sku: "BRE-PUM-MAN", unit: "Each Pump", price: 540.00 },
            { id: 10, name: "Cardiology IV Stethoscope", sku: "CAR-STH", unit: "Each Piece", price: 6880.00 },
            { id: 11, name: "Centrifuge Machine Electric (6 Tubes)", sku: "CEN-MAC-ELE", unit: "Each Machine", price: 8750.00 },
            { id: 12, name: "Clinical Thermometer", sku: "CLI-THR", unit: "Each Piece", price: 300.00 },
            { id: 13, name: "CPAP Ventmed Machine", sku: "CPA-VEN-MAC", unit: "Each Machine", price: 81250.00 },
            { id: 14, name: "Diagnostic Set", sku: "DIA-SET", unit: "Each Set", price: 8670.00 },
            { id: 15, name: "Digital Thermo Hygrometer", sku: "DIG-THR-HYG", unit: "Each Piece", price: 1600.00 },
            { id: 16, name: "Digital Thermometer", sku: "DIG-THR", unit: "Each Piece", price: 300.00 },
            { id: 17, name: "Doyen Retractor", sku: "DOY-RET", unit: "Each Piece", price: 2000.00 },
            { id: 18, name: "Drip Infusion Stand", sku: "DRI-INF-STD", unit: "Each Piece", price: 3380.00 },
            { id: 19, name: "Dust Coat", sku: "DUS-COA", unit: "Each Piece", price: 1000.00 },
            { id: 20, name: "Examination Couch", sku: "EXA-COU", unit: "Each Couch", price: 13130.00 },
            { id: 21, name: "Examination Light", sku: "EXA-LIG", unit: "Each Piece", price: 10630.00 },
            { id: 22, name: "Examination Light Adjustable", sku: "EXA-LIG-ADJ", unit: "Each Piece", price: 13750.00 },
            { id: 23, name: "Fetal Ultrasonic Doppler", sku: "FET-ULT-DOP", unit: "Each Piece", price: 5000.00 },
            { id: 24, name: "First Aid Box Medium", sku: "FIR-AID-MED", unit: "Each Kit", price: 2400.00 },
            { id: 25, name: "First Aid Box Small", sku: "FIR-AID-SML", unit: "Each Kit", price: 2000.00 },
            { id: 26, name: "First Aid Box Large Plastic", sku: "FIR-AID-LRG-PLA", unit: "Each Kit", price: 8670.00 },
            { id: 27, name: "First Aid Box Large Metal", sku: "FIR-AID-LRG-MET", unit: "Each Kit", price: 10000.00 },
            { id: 28, name: "Fridge Thermometer Analogue", sku: "FRI-THR-ANA", unit: "Each Thermometer", price: 820.00 },
            { id: 29, name: "Fridge Thermometer Digital", sku: "FRI-THR-DIG", unit: "Each Thermometer", price: 1070.00 },
            { id: 30, name: "HB Haemoglobin Machine", sku: "HBH-MAC", unit: "Each Machine", price: 10630.00 }
        ]
    },
    orthopedics: {
        name: "Orthopedics",
        description: "Orthopedic supplies, braces, and mobility aids",
        image: "instruments.png",
        icon: "fa-wheelchair",
        products: [
            { id: 1, name: "Commode Chair with Wheels", sku: "COM-CHR-WHL", unit: "Each Piece", price: 12700.00 },
            { id: 2, name: "Commode Chair without Wheels", sku: "COM-CHR-NO-WHL", unit: "Each Piece", price: 12700.00 },
            { id: 3, name: "Commode Seat", sku: "COM-SEA", unit: "Each Piece", price: 10000.00 },
            { id: 4, name: "Commode Seat with Castors", sku: "COM-SEA-CAS", unit: "Each Piece", price: 19400.00 },
            { id: 5, name: "Extrawide Shower Chair with Armrest (Height Adjustable)", sku: "EXT-SHO-CHR", unit: "Each Piece", price: 19400.00 },
            { id: 6, name: "Foldable Commode Seat", sku: "FOL-COM-SEA", unit: "Each Piece", price: 8700.00 },
            { id: 7, name: "Hydraulic Transfer Chair with Commode", sku: "HYD-TRA-CHR", unit: "Each Piece", price: 86700.00 },
            { id: 8, name: "Mechanical Transfer Chair with Commode", sku: "MEC-TRA-CHR", unit: "Each Piece", price: 73400.00 },
            { id: 9, name: "Reclining Commode Wheelchair", sku: "REC-COM-WHE", unit: "Each Piece", price: 33400.00 },
            { id: 10, name: "Shower Chair", sku: "SHO-CHR", unit: "Each Piece", price: 10000.00 },
            { id: 11, name: "Shower Chair with Armrest Height Adjustable", sku: "SHO-CHR-ARM", unit: "Each Piece", price: 12700.00 },
            { id: 12, name: "Standard Commode Wheelchair", sku: "STD-COM-WHE", unit: "Each Piece", price: 26000.00 },
            { id: 13, name: "Celebral Palsy Wheelchair", sku: "CEL-PAL-WHE", unit: "Each Piece", price: 60000.00 },
            { id: 14, name: "Electric Wheelchair", sku: "ELE-WHE", unit: "Each Piece", price: 173400.00 },
            { id: 15, name: "Extrawide Wheelchair", sku: "EXT-WHE", unit: "Each Piece", price: 30700.00 },
            { id: 16, name: "Orthopaedic Wheelchair", sku: "ORT-WHE", unit: "Each Piece", price: 24700.00 },
            { id: 17, name: "Paediatric Wheelchair", sku: "PED-WHE", unit: "Each Piece", price: 19400.00 },
            { id: 18, name: "Reclining Wheelchair", sku: "REC-WHE", unit: "Each Piece", price: 30700.00 },
            { id: 19, name: "Standard Wheelchair", sku: "STD-WHE", unit: "Each Piece", price: 16700.00 },
            { id: 20, name: "Adjustable Walking Stick", sku: "ADJ-WAL-STK", unit: "Each Piece", price: 1600.00 },
            { id: 21, name: "Axillary Crutches", sku: "AXI-CRU", unit: "Each Pair", price: 2700.00 },
            { id: 22, name: "Blind Canes", sku: "BLI-CAN", unit: "Each Piece", price: 2400.00 },
            { id: 23, name: "Elbow Crutches", sku: "ELB-CRU", unit: "Each Pair", price: 2700.00 },
            { id: 24, name: "Foldable Walking Stick", sku: "FOL-WAL-STK", unit: "Each Piece", price: 2000.00 },
            { id: 25, name: "Gutter Crutch", sku: "GUT-CRU", unit: "Each Pair", price: 6000.00 },
            { id: 26, name: "Parallel Bar", sku: "PAR-BAR", unit: "Each Piece", price: 42700.00 },
            { id: 27, name: "Quadripod Walking Stick", sku: "QUA-WAL-STK", unit: "Each Piece", price: 2700.00 },
            { id: 28, name: "Rollator", sku: "ROL", unit: "Each Piece", price: 17400.00 },
            { id: 29, name: "Sitting Aid", sku: "SIT-AID", unit: "Each Piece", price: 19400.00 },
            { id: 30, name: "Standing Aid", sku: "STA-AID", unit: "Each Piece", price: 32000.00 }
        ]
    }
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = productCategories;
}
